### ISSUE TITLE
华为云国际版跟国内版一样吗

### ISSUE THREAD

**Issue by nba6648780** [Arronlong/py_scripts#26]
华为云国际版好像不能用啊

**Comment by Arronlong** [comment]
有日志吗？

**Comment by nba6648780** [comment]
Run python scripts/cf2dns/cf2dns.py
  python scripts/cf2dns/cf2dns.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.10/x64/lib
    KEY: ***
    DOMAINS: ***
    ALIYUN_ACCESSKEY_ID: ***
    ALIYUN_ACCESSKEY_SECRET: ***
    QCLOUD_SECRET_ID: 
    QCLOUD_SECRET_KEY: 
    DNSPOD_LOGIN_ID: 
    DNSPOD_LOGIN_TOKEN: 
Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 127, in main
    cloud = getDnsApi(dns)
  File "scripts/cf2dns/cf2dns.py", line 109, in getDnsApi
    return HWCloudApi()
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 24, in __init__
    self.sign.Key = os.environ["HW_ACCESSKEY_ID"] #AK：BO9xxxxx
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'HW_ACCESSKEY_ID'
2021-04-03 01:40:25,527 - scripts/cf2dns/cf2dns.py[line:173] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-03 01:40:25----MESSAGE: 'HW_ACCESSKEY_ID'

**Comment by nba6648780** [comment]
配置都对

**Comment by Arronlong** [comment]
我的错，pull最新代码，或者按下图自行修改.github/workflows/action-cf2dns.yml 即可

![](https://cdn.jsdelivr.net/gh/Arronlong/cdn@master/blogImg/20210403232242.png)
