### ISSUE TITLE
华为云解析出现这个什么意思啊

### ISSUE THREAD

**Issue by nba6648780** [Arronlong/py_scripts#30]
python scripts/cf2dns/cf2dns.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.10/x64/lib
    KEY: ***
    DOMAINS: ***
    ALIYUN_ACCESSKEY_ID: 
    ALIYUN_ACCESSKEY_SECRET: 
    QCLOUD_SECRET_ID: 
    QCLOUD_SECRET_KEY: 
    DNSPOD_LOGIN_ID: 
    DNSPOD_LOGIN_TOKEN: 
    HW_ACCESSKEY_ID: ***
    HW_ACCESSKEY_SECRET: ***
Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 128, in main
    for domain, sub_domains in domains.items():
AttributeError: 'list' object has no attribute 'items'
2021-04-06 13:16:38,163 - scripts/cf2dns/cf2dns.py[line:173] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-06 13:16:38----MESSAGE: 'list' object has no attribute 'items'

**Comment by Arronlong** [comment]
环境变量DOMAINS 没有配置吧

> **DOMAINS**：域名信息，格式为{"DNS名":{"主域名":{"子域名":[路线数组]}}}，目前DNS名有：aliyun、qCloud、dnspod、hwCloud 分别对应支持的阿里云、腾讯云、Dnspod、华为云。路线有：CM、CU、CT ，其中CM：China Mobile 移动，CU：China Unicome 联通，CT：China Telecom 电信。

**Comment by nba6648780** [comment]
{"hwCloud":[{"biyi.com":{"@":["CM","CU","CT"],"www":["CM","CU","CT"]}},{"biy.com":{"@":["CM","CU","CT"],"www":["CM","CU","CT"]}}]}


这样对吗

**Comment by Arronlong** [comment]
> {"hwCloud":[{"biyi.com":{"@":["CM","CU","CT"],"www":["CM","CU","CT"]}},{"biy.com":{"@":["CM","CU","CT"],"www":["CM","CU","CT"]}}]}
> 
> 这样对吗

对的

**Comment by nba6648780** [comment]
全部设置对运行显示
Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 128, in main
    for domain, sub_domains in domains.items():
AttributeError: 'list' object has no attribute 'items'
2021-04-18 11:49:19,285 - scripts/cf2dns/cf2dns.py[line:173] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-18 11:49:19----MESSAGE: 'list' object has no attribute 'items'

**Comment by Arronlong** [comment]
拉取一下最新代码吧，已经修复了~
