### ISSUE TITLE
使用华为云DNS国际版出现报错

### ISSUE THREAD

**Issue by aaro-n** [Arronlong/py_scripts#32]
`Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 142, in main
    ret = cloud.get_record(domain, 100, sub_domain, "A")
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 88, in get_record
    zone_id = self.get_zone_id(domain)
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 32, in get_zone_id
    res = json.loads(requests.get(url, headers=r.headers).text.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
2021-04-21 20:59:47,918 - scripts/cf2dns/cf2dns.py[line:173] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-21 20:59:47----MESSAGE: 'str' object has no attribute 'decode'`

**Comment by aaro-n** [comment]
<img width="947" alt="截屏2021-04-22 上午5 10 43" src="https://user-images.githubusercontent.com/45537680/115621518-35691d80-a329-11eb-9fa1-3ba4ec43b5a2.png">

**Comment by Arronlong** [comment]
代码修复了，请拉取最新代码进行尝试
