### ISSUE TITLE
还是不行啊显示 看下

### ISSUE THREAD

**Issue by nba6648780** [Arronlong/py_scripts#34]
2021-04-25 06:56:53,704 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:53----MESSAGE: create_record() missing 1 required positional argument: 'ttl'
2021-04-25 06:56:53,705 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:53----MESSAGE: create_record() missing 1 required positional argument: 'ttl'
2021-04-25 06:56:53,706 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:53----MESSAGE: create_record() missing 1 required positional argument: 'ttl'
2021-04-25 06:56:55,671 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:55----MESSAGE: create_record() missing 1 required positional argument: 'ttl'
2021-04-25 06:56:55,671 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:55----MESSAGE: create_record() missing 1 required positional argument: 'ttl'
2021-04-25 06:56:55,671 - scripts/cf2dns/cf2dns.py[line:102] - ERROR: CHANGE DNS ERROR: ----Time: 2021-04-25 06:56:55----MESSAGE: create_record() missing 1 required positional argument: 'ttl'

**Comment by Arronlong** [comment]
我的错，忘记添加默认值了，现在加上了，你再更新一下代码吧

**Comment by nba6648780** [comment]
Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 15, in <module>
    from dns.hwcloud import HWCloudApi
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 19, in <module>
    class HWCloudApi:
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 138, in HWCloudApi
    def create_record(self, domain: str, sub_domain: str, value: list, record_type: str, line: strzz, ttl: int=300):
NameError: name 'strzz' is not defined
Error: Process completed with exit code 1.

**Comment by nba6648780** [comment]
你自己运行显示这个啊

**Comment by nba6648780** [comment]
显示更你的一模一样
