### ISSUE TITLE
华为云运行出现这个了

### ISSUE THREAD

**Issue by nba6648780** [Arronlong/py_scripts#35]
Traceback (most recent call last):
  File "scripts/cf2dns/cf2dns.py", line 15, in <module>
    from dns.hwcloud import HWCloudApi
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 19, in <module>
    class HWCloudApi:
  File "/home/runner/work/py_scripts/py_scripts/scripts/cf2dns/dns/hwcloud.py", line 138, in HWCloudApi
    def create_record(self, domain: str, sub_domain: str, value: list, record_type: str, line: strzz, ttl: int=300):
NameError: name 'strzz' is not defined
Error: Process completed with exit code 1.

你自己运行就这样

**Comment by doraemonlkmy** [comment]
大神，是不是str写错了呀？改成了str后还是报错scripts/cf2dns/cf2dns.py[line:169] - ERROR: CHANGE DNS ERROR: --------MESSAGE: list indices must be integers or slices, not str

**Comment by Arronlong** [comment]
好尴尬~已修复
